management:
    root: "./TEMPFOLDER"
    directories:
        - name: "/TEMP1/SUBTEMP1/SUBSUBTEMP1"
          rules:
            - pattern: "file_<mm>_<dd>_<yyyy>.txt"

        - name: "/TEMP1/SUBTEMP1"
          rules:
            - pattern: "file_<number>.txt"

        - name: "/TEMP2"
          rules:
            - pattern: "file_<*>.txt"
            - pattern: "<*>.txt"
